export const GROUPS = [
  {
    id: '0008a64a72654f6487f67efd9d66711d',
    title: 'Group 1',
    isInvitationOnly: false,
    owner: 'user_2',
    description: 'Group 1 description',
    snippet: 'Group 1 snippet',
    tags: ['Hub Group'],
    typeKeywords: [],
    phone: null,
    sortField: 'title',
    sortOrder: 'asc',
    isViewOnly: false,
    featuredItemsId: null,
    thumbnail: null,
    created: 1604076680000,
    modified: 1604076680000,
    access: 'public',
    capabilities: [],
    isFav: false,
    isReadOnly: false,
    protected: true,
    autoJoin: true,
    notificationsEnabled: false,
    provider: null,
    providerGroupName: null,
    leavingDisallowed: false,
    hiddenMembers: false,
    displaySettings: {
      itemTypes: '',
    },
    memberOrgIds: ['org_id_1'],
    properties: null,
    userMembership: {
      username: 'user_1',
      memberType: 'admin',
      applications: 0,
    },
  },
];
export const CHANNEL = {
  allowReply: true,
  allowAsAnonymous: false,
  softDelete: true,
  defaultPostStatus: 'approved',
  allowReaction: true,
  id: 'c1f592e6c6a84a37b94613df3683f5e5',
  access: 'public',
  orgs: [],
  groups: ['0008a64a72654f6487f67efd9d66711d'],
  creator: 'user_3',
  editor: 'user_3',
  createdAt: new Date('2021-07-22T15:12:10.970Z'),
  updatedAt: new Date('2021-07-22T15:12:10.970Z'),
};
export const POST = {
  id: '24df9b6686d14ed9b3a4a3edeb702c07',
  title: 'User 4 post',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  discussion: 'hub://group/23240df5ca77439dbb0438af077e7878',
  creator: 'user_4',
  editor: 'user_4',
  createdAt: new Date('2021-09-29T18:57:58.066Z'),
  updatedAt: new Date('2021-09-29T18:57:58.066Z'),
  status: 'approved',
  geometry: null,
  appInfo: null,
  parent: null,
  replyCount: 2,
};
export const CREATOR = {
  username: 'user_4',
  fullName: 'User 4',
  firstName: 'User',
  lastName: '4',
  preferredView: null,
  description: 'You may also know me as User 4.',
  email: 'user4@esri.com',
  idpUsername: null,
  favGroupId: 'c4497a77b7a0438b94e3e941a73e25cb',
  lastLogin: 1641918016000,
  mfaEnabled: false,
  storageUsage: 2514975382,
  storageQuota: 2199023255552,
  orgId: 'org_id_1',
  role: 'org_admin',
  privileges: [
    'features:user:edit',
    'portal:admin:assignToGroups',
    'portal:admin:createUpdateCapableGroup',
    'portal:admin:viewGroups',
    'portal:admin:viewUsers',
    'portal:publisher:publishFeatures',
    'portal:publisher:publishScenes',
    'portal:publisher:publishTiles',
    'portal:user:addExternalMembersToGroup',
    'portal:user:createGroup',
    'portal:user:createItem',
    'portal:user:invitePartneredCollaborationMembers',
    'portal:user:joinGroup',
    'portal:user:joinNonOrgGroup',
    'portal:user:shareGroupToOrg',
    'portal:user:shareGroupToPublic',
    'portal:user:shareToGroup',
    'portal:user:shareToOrg',
    'portal:user:shareToPublic',
    'portal:user:viewOrgGroups',
    'portal:user:viewOrgItems',
    'portal:user:viewOrgUsers',
    'premium:user:demographics',
    'premium:user:featurereport',
    'premium:user:geocode',
    'premium:user:geocode:stored',
    'premium:user:geocode:temporary',
    'premium:user:geoenrichment',
    'premium:user:networkanalysis',
    'premium:user:networkanalysis:closestfacility',
    'premium:user:networkanalysis:locationallocation',
    'premium:user:networkanalysis:optimizedrouting',
    'premium:user:networkanalysis:origindestinationcostmatrix',
    'premium:user:networkanalysis:routing',
    'premium:user:networkanalysis:servicearea',
    'premium:user:networkanalysis:vehiclerouting',
    'premium:user:spatialanalysis',
  ],
  roleId: 'role_id_1',
  level: '2',
  disabled: false,
  tags: [],
  culture: 'en-AU',
  region: 'US',
  units: 'english',
  thumbnail: 'hub-profile-15598402608311.png',
  access: 'public',
  created: 1558412566000,
  modified: 1616690771000,
  provider: 'arcgis',
  groups: GROUPS,
};
export const ORGANIZATION = {
  id: 'org_id_1',
  isPortal: true,
  name: 'hubqa'
};
export const CONTEXT = {
  id: 123,
  currentUser: CREATOR,
  portalUrl: 'https://qaext.arcgis.com/sharing/rest',
  session: {
    portal: 'https://somewhere.arcigis.com/sharing/rest',
    token: 'token-123'
  },
  portalSelf: {
    id: '123',
    name: 'My org',
    isPortal: false,
    urlKey: 'www'
  },
  serviceStatus: {
    portal: "online",
    discussions: "online",
    events: "online",
    metrics: "online",
    notifications: "online",
    "hub-search": "online",
    domains: "online",
  }
};
