export var SCREEN_SIZE;
(function (SCREEN_SIZE) {
  SCREEN_SIZE[SCREEN_SIZE["EXTRA_SMALL"] = 576] = "EXTRA_SMALL";
  SCREEN_SIZE[SCREEN_SIZE["SMALL"] = 768] = "SMALL";
  SCREEN_SIZE[SCREEN_SIZE["MEDIUM"] = 992] = "MEDIUM";
  SCREEN_SIZE[SCREEN_SIZE["LARGE"] = 1200] = "LARGE";
})(SCREEN_SIZE || (SCREEN_SIZE = {}));
