import { ArcGISContext } from "@esri/hub-common";
export const GROUPS = [
  {
    id: '0008a64a72654f6487f67efd9d66711d',
    title: 'Group 1',
    isInvitationOnly: false,
    owner: 'user_2',
    description: 'Group 1 description',
    snippet: 'Group 1 snippet',
    tags: ['Hub Group'],
    typeKeywords: [],
    phone: null,
    sortField: 'title',
    sortOrder: 'asc',
    isViewOnly: false,
    featuredItemsId: null,
    thumbnail: null,
    created: 1604076680000,
    modified: 1604076680000,
    access: 'public',
    capabilities: [],
    isFav: false,
    isReadOnly: false,
    protected: true,
    autoJoin: true,
    notificationsEnabled: false,
    provider: null,
    providerGroupName: null,
    leavingDisallowed: false,
    hiddenMembers: false,
    displaySettings: {
      itemTypes: '',
    },
    memberOrgIds: ['org_id_1'],
    properties: null,
    userMembership: {
      username: 'user_1',
      memberType: 'admin',
      applications: 0,
    },
  },
];
export const USER = {
  username: 'user_1',
  fullName: 'User 1',
  firstName: 'User',
  lastName: '1',
  preferredView: null,
  description: 'You may also know me as User 1.',
  email: 'user4@esri.com',
  idpUsername: null,
  favGroupId: 'c4497a77b7a0438b94e3e941a73e25cb',
  lastLogin: 1641918016000,
  mfaEnabled: false,
  storageUsage: 2514975382,
  storageQuota: 2199023255552,
  orgId: 'org_id_1',
  role: 'org_admin',
  privileges: [
    'features:user:edit',
    'portal:admin:assignToGroups',
    'portal:admin:createUpdateCapableGroup',
    'portal:admin:viewGroups',
    'portal:admin:viewUsers',
    'portal:publisher:publishFeatures',
    'portal:publisher:publishScenes',
    'portal:publisher:publishTiles',
    'portal:user:addExternalMembersToGroup',
    'portal:user:createGroup',
    'portal:user:createItem',
    'portal:user:invitePartneredCollaborationMembers',
    'portal:user:joinGroup',
    'portal:user:joinNonOrgGroup',
    'portal:user:shareGroupToOrg',
    'portal:user:shareGroupToPublic',
    'portal:user:shareToGroup',
    'portal:user:shareToOrg',
    'portal:user:shareToPublic',
    'portal:user:viewOrgGroups',
    'portal:user:viewOrgItems',
    'portal:user:viewOrgUsers',
    'premium:user:demographics',
    'premium:user:featurereport',
    'premium:user:geocode',
    'premium:user:geocode:stored',
    'premium:user:geocode:temporary',
    'premium:user:geoenrichment',
    'premium:user:networkanalysis',
    'premium:user:networkanalysis:closestfacility',
    'premium:user:networkanalysis:locationallocation',
    'premium:user:networkanalysis:optimizedrouting',
    'premium:user:networkanalysis:origindestinationcostmatrix',
    'premium:user:networkanalysis:routing',
    'premium:user:networkanalysis:servicearea',
    'premium:user:networkanalysis:vehiclerouting',
    'premium:user:spatialanalysis',
  ],
  roleId: 'role_id_1',
  level: '2',
  disabled: false,
  tags: [],
  culture: 'en-AU',
  region: 'US',
  units: 'english',
  thumbnail: 'hub-profile-15598402608355.png',
  access: 'public',
  created: 1558412566000,
  modified: 1616690771000,
  provider: 'arcgis',
  groups: GROUPS,
};
export const ENTITY = {
  "id": "bc3",
  "itemControl": "",
  "owner": "mockOwner",
  "schemaVersion": 1,
  "tags": [],
  "type": "Web Map",
  "canEdit": true,
  "canDelete": true,
  "name": "Mock Entity",
  "thumbnail": "cat.png",
  "typeKeywords": [],
};
export const CONTEXT = new ArcGISContext({
  id: 123,
  currentUser: USER,
  portalUrl: 'https://qaext.arcgis.com/sharing/rest',
  serviceStatus: {
    portal: "online",
    discussions: "online",
    events: "online",
    metrics: "online",
    notifications: "online",
    "hub-search": "online",
    domains: "online",
    "hub-downloads": "online",
  }
});
