import { IGroup, IUser, IPortal } from '@esri/arcgis-rest-portal';
import { IChannel, IPost } from '@esri/hub-discussions';
import { IArcGISContext, IHubContent } from '@esri/hub-common';
import { Feature, Geometry } from 'geojson';
export declare const ORGANIZATION: IPortal;
export declare const GROUPS: IGroup[];
export declare const USER: IUser;
export declare const POSTCREATOR: {
  username: string;
  fullName: string;
  firstName: string;
  lastName: string;
  description: string;
  email: string;
  availableCredits?: number;
  assignedCredits?: number;
  preferredView?: any;
  idpUsername?: string;
  favGroupId?: string;
  lastLogin?: number;
  mfaEnabled?: boolean;
  access?: string;
  storageUsage?: number;
  storageQuota?: number;
  orgId?: string;
  cOrgId?: string;
  role?: "org_admin" | "org_publisher" | "org_user";
  privileges?: string[];
  roleId?: string;
  level?: string;
  disabled?: boolean;
  units?: string;
  tags?: string[];
  culture?: string;
  region?: string;
  thumbnail?: string;
  created?: number;
  modified?: number;
  groups?: IGroup[];
  provider?: "enterprise" | "arcgis" | "facebook" | "google";
};
export declare const PARENTCREATOR: {
  username: string;
  fullName: string;
  firstName: string;
  lastName: string;
  description: string;
  email: string;
  availableCredits?: number;
  assignedCredits?: number;
  preferredView?: any;
  idpUsername?: string;
  favGroupId?: string;
  lastLogin?: number;
  mfaEnabled?: boolean;
  access?: string;
  storageUsage?: number;
  storageQuota?: number;
  orgId?: string;
  cOrgId?: string;
  role?: "org_admin" | "org_publisher" | "org_user";
  privileges?: string[];
  roleId?: string;
  level?: string;
  disabled?: boolean;
  units?: string;
  tags?: string[];
  culture?: string;
  region?: string;
  thumbnail?: string;
  created?: number;
  modified?: number;
  groups?: IGroup[];
  provider?: "enterprise" | "arcgis" | "facebook" | "google";
};
export declare const CHANNEL: IChannel;
export declare const PARENT: IPost;
export declare const POST: IPost;
export declare const CONTEXT: IArcGISContext;
export declare const GEOMETRY: Geometry;
export declare const FEATURE: Feature;
export declare const CONTENT: IHubContent;
