import { IGroup, IPortal, IUser } from '@esri/arcgis-rest-portal';
import { IChannel, IPost } from '@esri/hub-discussions';
import { IArcGISContext } from '@esri/hub-common';
import { Feature, Geometry } from 'geojson';
import { IMentionedUserDetails } from '../../../../utils/discussions/types';
export declare const GROUPS: IGroup[];
export declare const CHANNEL: IChannel;
export declare const POST: IPost;
export declare const JULIANA: IUser;
export declare const PAIGE: {
  username: string;
  fullName: string;
  firstName: string;
  lastName: string;
  id: string;
  availableCredits?: number;
  assignedCredits?: number;
  preferredView?: any;
  description?: string;
  email?: string;
  idpUsername?: string;
  favGroupId?: string;
  lastLogin?: number;
  mfaEnabled?: boolean;
  access?: string;
  storageUsage?: number;
  storageQuota?: number;
  orgId?: string;
  cOrgId?: string;
  role?: "org_admin" | "org_publisher" | "org_user";
  privileges?: string[];
  roleId?: string;
  level?: string;
  disabled?: boolean;
  units?: string;
  tags?: string[];
  culture?: string;
  region?: string;
  thumbnail?: string;
  created?: number;
  modified?: number;
  groups?: IGroup[];
  provider?: "enterprise" | "arcgis" | "facebook" | "google";
};
export declare const CHEZELLE: {
  username: string;
  fullName: string;
  firstName: string;
  lastName: string;
  id: string;
  availableCredits?: number;
  assignedCredits?: number;
  preferredView?: any;
  description?: string;
  email?: string;
  idpUsername?: string;
  favGroupId?: string;
  lastLogin?: number;
  mfaEnabled?: boolean;
  access?: string;
  storageUsage?: number;
  storageQuota?: number;
  orgId?: string;
  cOrgId?: string;
  role?: "org_admin" | "org_publisher" | "org_user";
  privileges?: string[];
  roleId?: string;
  level?: string;
  disabled?: boolean;
  units?: string;
  tags?: string[];
  culture?: string;
  region?: string;
  thumbnail?: string;
  created?: number;
  modified?: number;
  groups?: IGroup[];
  provider?: "enterprise" | "arcgis" | "facebook" | "google";
};
export declare const CORY: {
  username: string;
  fullName: string;
  firstName: string;
  lastName: string;
  id: string;
  availableCredits?: number;
  assignedCredits?: number;
  preferredView?: any;
  description?: string;
  email?: string;
  idpUsername?: string;
  favGroupId?: string;
  lastLogin?: number;
  mfaEnabled?: boolean;
  access?: string;
  storageUsage?: number;
  storageQuota?: number;
  orgId?: string;
  cOrgId?: string;
  role?: "org_admin" | "org_publisher" | "org_user";
  privileges?: string[];
  roleId?: string;
  level?: string;
  disabled?: boolean;
  units?: string;
  tags?: string[];
  culture?: string;
  region?: string;
  thumbnail?: string;
  created?: number;
  modified?: number;
  groups?: IGroup[];
  provider?: "enterprise" | "arcgis" | "facebook" | "google";
};
export declare const ORGANIZATION: IPortal;
export declare const CONTEXT: IArcGISContext;
export declare const MENTIONEDUSERS: IMentionedUserDetails[];
export declare const GEOMETRY: Geometry;
export declare const FEATURE: Feature;
