import { r as registerInstance, c as createEvent, h, H as Host, a as getElement } from './index-57f71b44.js';
import { i as intlManager } from './intl-manager-13176c32.js';
import { b as bind } from './context-7d8f7366.js';
import { a as cloneObject } from './util-3e6872d9.js';
import './index-213c70d0.js';
import './interfaces-fd83cf89.js';
import './get-prop-ec5be510.js';

const SCHEMA = {
  required: [],
  type: 'object',
  properties: {
    icon: {
      type: 'object',
      properties: {
        scope: {
          type: 'string',
          default: 'library',
          enum: ['library', 'url']
        },
        name: {
          type: 'string'
        },
        url: {
          type: 'string'
        },
        color: {
          type: 'string',
        },
        altText: {
          type: 'string'
        }
      }
    }
  }
};
const UI_SCHEMA = {
  type: 'Layout',
  elements: [
    {
      scope: '/properties/icon/properties/scope',
      type: 'Control',
      options: {
        control: 'hub-field-input-radio',
        enum: {
          i18nScope: 'scope.enum'
        }
      }
    },
    {
      type: 'Slot',
      options: { name: 'select-icon-button' },
      rule: {
        effect: 'HIDE',
        condition: {
          scope: '/properties/icon/properties/scope',
          schema: { const: 'url' }
        }
      }
    },
    {
      scope: '/properties/icon/properties/url',
      type: 'Control',
      rule: {
        effect: 'SHOW',
        condition: {
          scope: '/properties/icon/properties/scope',
          schema: { const: 'url' }
        }
      }
    },
    {
      scope: '/properties/icon/properties/color',
      type: 'Control',
      options: {
        control: 'hub-field-input-color'
      }
    },
    {
      labelKey: 'altText.label',
      scope: '/properties/icon/properties/altText',
      type: 'Control',
      options: {
        helperText: {
          labelKey: 'altText.helperText'
        }
      }
    }
  ]
};

// NOTE: this was generated from @esri/calcite-ui-icons@v3.22.1
// if we end up using this component in production
// we should add @esri/calcite-ui-icons as a dependency
// and create a script that generates this file and
// run it every time we update @esri/calcite-ui-icons
const iconNames = [
  "aZ",
  "aZDown",
  "aZUp",
  "accessStringResults",
  "activityMonitor",
  "actualSize",
  "addIn",
  "addInEdit",
  "addInNew",
  "addLayer",
  "addReaction",
  "addText",
  "addressBook",
  "allServers",
  "altitude",
  "analysis",
  "analysisOverlay",
  "annotateTool",
  "antennaHeight",
  "appGear",
  "appLauncher",
  "appRun",
  "appUpdate",
  "applications",
  "apps",
  "arcgisOnline",
  "arrowBoldDown",
  "arrowBoldLeft",
  "arrowBoldRight",
  "arrowBoldUp",
  "arrowDoubleDiagonal1",
  "arrowDoubleDiagonal2",
  "arrowDoubleHorizontal",
  "arrowDoubleVertical",
  "arrowDown",
  "arrowDownLeft",
  "arrowDownRight",
  "arrowLeft",
  "arrowRight",
  "arrowRightLeft",
  "arrowUp",
  "arrowUpDown",
  "arrowUpLeft",
  "arrowUpRight",
  "article",
  "asteriskLarge",
  "asteriskSmall",
  "attachment",
  "attachmentPlus",
  "automation",
  "banana",
  "basemap",
  "battery1",
  "battery2",
  "battery3",
  "battery4",
  "batteryCharging",
  "beacon",
  "beaker",
  "bearLeft",
  "bearRight",
  "beginning",
  "bell",
  "bellOff",
  "beta",
  "biking",
  "blank",
  "blog",
  "bluetooth",
  "bold",
  "book",
  "bookmark",
  "boolean",
  "borderRadiusFullyRounded",
  "borderRadiusRounded",
  "borderRadiusSharp",
  "boxChart",
  "bracketsCurly",
  "brightness",
  "bringForward",
  "bringToFront",
  "browser",
  "browserMap",
  "brushMark",
  "brushMarkPlus",
  "brushTip",
  "bulletPoint",
  "button",
  "calculator",
  "calendar",
  "camera",
  "cameraFlashOff",
  "cameraFlashOn",
  "cameraPlus",
  "cameraSwitchFrontBack",
  "cameraUnlock",
  "car",
  "caretDoubleHorizontal",
  "caretDoubleVertical",
  "caretDown",
  "caretLeft",
  "caretRight",
  "caretSquareDown",
  "caretSquareLeft",
  "caretSquareRight",
  "caretSquareUp",
  "caretUp",
  "catalogDataset",
  "centerAlign",
  "centerHorizontal",
  "centerVertical",
  "certificate",
  "changeDetection",
  "changeFontSize",
  "chartGear",
  "chartMagnifyingGlass",
  "check",
  "checkCircle",
  "checkExtent",
  "checkLayer",
  "checkShield",
  "checkSquare",
  "chevronDown",
  "chevronLeft",
  "chevronRight",
  "chevronUp",
  "chevronsDown",
  "chevronsLeft",
  "chevronsRight",
  "chevronsUp",
  "chordDiagram",
  "circle",
  "circleArea",
  "circleDisallowed",
  "classifyObjects",
  "classifyPixels",
  "clipboard",
  "clock",
  "clockDown",
  "clockForward",
  "clockUp",
  "cloud",
  "cloudy",
  "clustering",
  "code",
  "collaboration",
  "collaborationDistributed",
  "collection",
  "colorCodedMap",
  "colorCorrection",
  "compactness",
  "compare",
  "compass",
  "compassNeedle",
  "compassNorthCircle",
  "conditionalRules",
  "conditionalRulesPath",
  "conferenceRoom",
  "configure",
  "configurePopup",
  "console",
  "contentFull",
  "contentInline",
  "contentLarge",
  "contentMedium",
  "contentMinimal",
  "contentNone",
  "contentSideBySide",
  "contentSmall",
  "contingentValues",
  "contract",
  "contrast",
  "convert",
  "coordinateSystem",
  "copy",
  "copyToClipboard",
  "creditCard",
  "credits",
  "crop",
  "cube",
  "cursor",
  "cursorClick",
  "cursorLock",
  "cursorMarquee",
  "cursorPlus",
  "cursorSelection",
  "cutAndFillVolumeCalculation",
  "dashboard",
  "data",
  "dataCheck",
  "dataClockChart",
  "dataCloud",
  "dataFolder",
  "dataMagnifyingGlass",
  "dataRaster",
  "debug",
  "debugScript",
  "decreaseLinkChartSymbolSize",
  "deepLearning",
  "deepLearningProject",
  "description",
  "desk",
  "desktop",
  "diamond",
  "dimensions",
  "discard",
  "disembark",
  "displaySelectionLock",
  "displaySelectionUnlock",
  "dissolveFeatures",
  "distanceType",
  "distributeHeightEvenly",
  "distributeWidthEvenly",
  "dockBottom",
  "dockLeft",
  "dockRight",
  "download",
  "downloadTo",
  "drag",
  "driveTime",
  "driveTimeLargest",
  "driveTimeSmallest",
  "driveTimeThreshold",
  "driveTimeXBar",
  "drivingDistance",
  "drivingTime",
  "droneFixedWing",
  "droneFlyingWing",
  "droneQuadcopter",
  "droneQuadcopterTop",
  "duplicate",
  "editAttributes",
  "education",
  "effects",
  "elevator",
  "elevatorDown",
  "elevatorUp",
  "ellipse",
  "ellipsis",
  "ellipsisCircle",
  "emailAddress",
  "embark",
  "embeddedCard",
  "embeddedContent",
  "embeddedLiveContent",
  "end",
  "envelope",
  "erase",
  "escalator",
  "escalatorDown",
  "escalatorUp",
  "event",
  "exclamationMarkCircle",
  "exclamationMarkTriangle",
  "exitHighwayLeft",
  "exitHighwayRight",
  "expand",
  "explore",
  "export",
  "extent",
  "extentFilter",
  "eyedropper",
  "faceId",
  "featureDetails",
  "featureLayer",
  "file",
  "fileArchive",
  "fileCad",
  "fileCode",
  "fileCsv",
  "fileData",
  "fileEcd",
  "fileExcel",
  "fileGpx",
  "fileImage",
  "fileKml",
  "fileMagnifyingGlass",
  "filePdf",
  "filePdfPlus",
  "filePitemx",
  "filePpt",
  "fileReport",
  "fileShape",
  "fileSound",
  "fileSqlite",
  "fileText",
  "fileVideo",
  "fileWord",
  "fileZip",
  "files",
  "filesCsvCollection",
  "filter",
  "findPath",
  "fingerprint",
  "flash",
  "flip",
  "floorPlan",
  "fog",
  "folder",
  "folderArchive",
  "folderMove",
  "folderNew",
  "folderOpen",
  "folderPlus",
  "folderStar",
  "folders",
  "follow",
  "followPause",
  "followPlay",
  "footer",
  "footprint",
  "forkLeft",
  "forkMiddle",
  "forkRight",
  "formDropdown",
  "formElements",
  "formField",
  "formFieldMultiline",
  "formFieldOff",
  "forward",
  "freehand",
  "freehandArea",
  "frown",
  "fullScreen",
  "fullScreenExit",
  "function",
  "functionEditor",
  "gallery",
  "gamma",
  "gauge",
  "gaugeSummary",
  "gear",
  "geoanalyticsServer",
  "geoeventServer",
  "geographicLinkChartLayout",
  "geonet",
  "geonetQuestion",
  "gisServer",
  "globe",
  "gpsOff",
  "gpsOn",
  "graphAxis",
  "graphBar100Stacked",
  "graphBar",
  "graphBarSideBySide",
  "graphBarStacked",
  "graphGuides",
  "graphHistogram",
  "graphLineSeries",
  "graphMovingAverage",
  "graphPieSlice",
  "graphScatterPlot",
  "graphTimeSeries",
  "grid",
  "gridDiamond",
  "gridHexagon",
  "gridTriangle",
  "gridUnit",
  "group",
  "groupForm",
  "groupFormPlus",
  "groupItems",
  "groupLayoutElements",
  "groupX",
  "halo",
  "hamburger",
  "hammer",
  "handleVertical",
  "heading",
  "headingLayout",
  "headingRtl",
  "headset",
  "heart",
  "heatChart",
  "heavyRain",
  "heavySnow",
  "hideEmpty",
  "highlighter",
  "highlighterTip",
  "highwayChange",
  "highwayChangeRight",
  "hillshadeEffect",
  "home",
  "horizontalDistribute",
  "hourglassActive",
  "hourglassExpired",
  "i12X",
  "i14X",
  "i18X",
  "i1X",
  "i2DExplore",
  "i2X",
  "i360View",
  "i3DGlasses",
  "i4X",
  "i8X",
  "image",
  "imageChips",
  "imageDisplayOrder",
  "imageLayer",
  "imageMensuration",
  "imagePin",
  "imagePlus",
  "imageSegmentation",
  "imageServer",
  "imageSpace",
  "imageUnit",
  "images",
  "import",
  "inbox",
  "increaseLinkChartSymbolSize",
  "indicator",
  "infographic",
  "information",
  "informationLetter",
  "initiative",
  "initiativeTemplate",
  "insets",
  "inspection",
  "integer",
  "investigation",
  "italicize",
  "key",
  "keyboard",
  "keypad",
  "knowledgeGraph",
  "knowledgeGraphDashboard",
  "knowledgeGraphDataModel",
  "knowledgeGraphExport",
  "knowledgeGraphImport",
  "knowledgeGraphNew",
  "knowledgeGraphRelationship",
  "knowledgeLayer",
  "knowledgeServer",
  "label",
  "labelOff",
  "language",
  "languageTranslate",
  "lasso",
  "lassoSelect",
  "launch",
  "layer",
  "layerBasemap",
  "layerBroken",
  "layerFilter",
  "layerGraphics",
  "layerHide",
  "layerKml",
  "layerLine",
  "layerLineService",
  "layerMap",
  "layerMapService",
  "layerPoints",
  "layerPolygon",
  "layerPolygonService",
  "layerService",
  "layerZoomTo",
  "layers",
  "layersEditable",
  "layersReference",
  "layoutHorizontal",
  "layoutVertical",
  "left",
  "leftAlign",
  "leftEdge",
  "leftLeft",
  "leftRight",
  "legend",
  "legendLeft",
  "legendPlus",
  "legendRight",
  "license",
  "lightRain",
  "lightSnow",
  "lightbulb",
  "line",
  "lineCheck",
  "lineDashed",
  "lineDotted",
  "lineOfSight",
  "lineSolid",
  "lineStraight",
  "link",
  "linkChart",
  "list",
  "listBullet",
  "listButton",
  "listCheck",
  "listCheckAll",
  "listMerge",
  "listNumber",
  "listNumberRtl",
  "listRadio",
  "listRectangle",
  "listShowAll",
  "locator",
  "lock",
  "ltrElementsAlign",
  "ltrParagraphAlign",
  "magnifyingGlass",
  "magnifyingGlassMinus",
  "magnifyingGlassPlus",
  "map",
  "mapContents",
  "mapPin",
  "mapSpace",
  "marketplace",
  "maximize",
  "maximum",
  "maximumGraph",
  "maximumTerritoryDistance",
  "measure",
  "measureArea",
  "measureBuildingHeightShadow",
  "measureBuildingHeightTopBase",
  "measureBuildingHeightTopShadow",
  "measureLine",
  "mediaLayer",
  "megaPhone",
  "merge",
  "mergeOnHighway",
  "mergeOnHighwayRight",
  "microphone",
  "microphonePlus",
  "minDistanceBetweenCenters",
  "minimize",
  "minimum",
  "minimumGraph",
  "minus",
  "minusCircle",
  "minusSquare",
  "miscellaneousCollection",
  "missionServer",
  "mobile",
  "mobileOff",
  "mobileVibrate",
  "monitor",
  "moon",
  "move",
  "moveUp",
  "moveUpAll",
  "mu",
  "multidimensionalRaster",
  "multipleVariables",
  "musicNote",
  "newRasterFunctionTemplate",
  "newTraining",
  "noAttachment",
  "noImage",
  "noMap",
  "nodesLink",
  "nodesMerge",
  "nodesUnlink",
  "nodesUnmerge",
  "notebook",
  "notebookServer",
  "notebookSnapshot",
  "null",
  "number",
  "numberCircle1",
  "numberCircle2",
  "numberCircle3",
  "numberCircle4",
  "numberCircle5",
  "numberCircle6",
  "numberCircle7",
  "numberCircle8",
  "numberCircle9",
  "numberOfTerritories",
  "objectDetection",
  "offline",
  "online",
  "openBook",
  "organization",
  "orientedImageryWidget",
  "outbox",
  "overlapFeatures",
  "overview",
  "package",
  "paintBucket",
  "palette",
  "paletteCheck",
  "pan",
  "panDrag",
  "partlyCloudy",
  "paste",
  "pause",
  "pen",
  "penMark",
  "penMarkPlus",
  "penTip",
  "pencil",
  "pencilMark",
  "pencilMarkPlus",
  "pencilSquare",
  "pencilTip",
  "pentagon",
  "percent",
  "person",
  "person2",
  "personalHomepage",
  "phone",
  "pieChart",
  "pin",
  "pinPlus",
  "pinTear",
  "pins",
  "plane",
  "plans",
  "play",
  "plus",
  "plusCircle",
  "plusSquare",
  "point",
  "polygon",
  "polygonArea",
  "polygonLineCheck",
  "polygonVertices",
  "popUp1",
  "popUpBlank",
  "popup",
  "portal",
  "premiumContentUserCredit",
  "presentation",
  "preserve",
  "print",
  "printPreview",
  "processingTemplates",
  "profileVariables",
  "projects",
  "pushpin",
  "puzzlePiece",
  "qrCode",
  "qtCode",
  "question",
  "questionMark",
  "quote",
  "rain",
  "rainSnow",
  "rainThunder",
  "rampLeft",
  "rampRight",
  "rangefinder",
  "rasterAnalysis",
  "rasterFunction",
  "rasterFunctionTemplate",
  "readOnlyNonEditable",
  "recent",
  "rectangle",
  "rectangleArea",
  "rectanglePlus",
  "recurrence",
  "redo",
  "refresh",
  "register",
  "reorderCards",
  "reorderGrid",
  "reorderStack",
  "replaceImage",
  "reset",
  "resizeArea",
  "retrain",
  "reverse",
  "rfid",
  "rhombus",
  "ribbon",
  "ribbonRosette",
  "right",
  "rightAlign",
  "rightEdge",
  "rightLeft",
  "rightRight",
  "rings",
  "ringsLargest",
  "ringsSmallest",
  "ringsThreshold",
  "ringsXBar",
  "roadSign",
  "rosette",
  "rotate",
  "rotateDevice",
  "roundAbout",
  "roundAboutRight",
  "roundedRectangle",
  "routeFrom",
  "routeTo",
  "rtlElementsAlign",
  "rtlParagraphAlign",
  "running",
  "runningOutline",
  "ruralDrivingDistance",
  "ruralDrivingTime",
  "satellite0",
  "satellite1",
  "satellite2",
  "satellite3",
  "save",
  "scanBarcode",
  "scissors",
  "screenshotMode",
  "script",
  "seamlines",
  "search",
  "security",
  "select",
  "selectCategory",
  "selectRange",
  "selectVisible",
  "selectedItemsFilter",
  "selection",
  "selectionFilter",
  "selectionX",
  "send",
  "sendBackwards",
  "sendToBack",
  "sensor",
  "separator",
  "serialPort",
  "server",
  "serverLock",
  "services",
  "shapes",
  "share",
  "shareIos",
  "sharpLeft",
  "sharpRight",
  "shieldCoin",
  "shoppingCart",
  "showColumn",
  "showMultipleLayersAtATime",
  "showOneLayerAtATime",
  "sidecar",
  "sigma",
  "signIn",
  "signOut",
  "skyPlot",
  "slice",
  "sliders",
  "slidersHorizontal",
  "slideshow",
  "smartCamera",
  "smartForm",
  "smile",
  "snapToGrid",
  "snapToPixel",
  "snapToPoint",
  "snow",
  "snowThunder",
  "sortAscending",
  "sortAscendingArrow",
  "sortDescending",
  "sortDescendingArrow",
  "sound",
  "soundLow",
  "soundOff",
  "soundUnavailable",
  "speechBubble",
  "speechBubbleCheck",
  "speechBubbleExclamation",
  "speechBubblePlus",
  "speechBubbleSocial",
  "speechBubbles",
  "spinner",
  "split",
  "splitFeatures",
  "square",
  "squareArea",
  "stairs",
  "stairsDown",
  "stairsUp",
  "star",
  "starCircle",
  "straight",
  "string",
  "subheading1",
  "subheading",
  "subheading2",
  "subheading3",
  "subheading4",
  "subheading5",
  "subheadingRtl",
  "submit",
  "subscript",
  "suitabilityAnalysisOutput",
  "summarizeCenterAndDispersion1",
  "summarizeCenterAndDispersion2",
  "summarizeCenterAndDispersion3",
  "summary",
  "superimpose",
  "superscript",
  "survey",
  "switch",
  "systemManagement",
  "tabbedView",
  "table",
  "tables",
  "tablet",
  "tag",
  "takePedestrianRamp",
  "terminal",
  "territoryBufferDistance",
  "testData",
  "text",
  "textLarge",
  "textMedium",
  "textParagraphLarge",
  "textSmall",
  "thumbsDown",
  "thumbsUp",
  "tileLayer",
  "tiledImageryLayer",
  "timer",
  "title",
  "toggle",
  "toggleOff",
  "toggleOn",
  "touch",
  "tour",
  "tourPinTear",
  "transparency",
  "trapezoidArea",
  "trash",
  "triangle",
  "truckingDistance",
  "truckingTime",
  "uTurn",
  "uTurnRight",
  "underline",
  "undo",
  "ungroupItems",
  "ungroupLayoutElements",
  "unlink",
  "unlock",
  "unpin",
  "unregister",
  "unselected",
  "upload",
  "uploadTo",
  "urbanModel",
  "usbSecurityKey",
  "user",
  "userDown",
  "userKey",
  "userMinus",
  "userPlus",
  "userToDevice",
  "userUp",
  "userX",
  "users",
  "utilityNetworkTrace",
  "vertexCheck",
  "vertexEdit",
  "vertexGps",
  "vertexMove",
  "vertexPlus",
  "vertexX",
  "verticalDistribute",
  "video",
  "videoPlus",
  "videoServer",
  "videoSingleServer",
  "videoWeb",
  "viewHide",
  "viewMixed",
  "viewVisible",
  "viewshed",
  "walkThroughDoor",
  "walking",
  "walkingDistance",
  "walkingTime",
  "web",
  "webhook",
  "wheelchair",
  "widgetsGroup",
  "widgetsSource",
  "widgetsTabs",
  "wifi",
  "workflowDiagram",
  "workflowManagerServer",
  "wrench",
  "x",
  "xAxisGuide",
  "xBar",
  "xCircle",
  "xOctagon",
  "yAxisGuide",
  "zoomInFixed",
  "zoomOutFixed",
  "zoomToObject"
];

const Icon = class {
  constructor(hostRef) {
    registerInstance(this, hostRef);
    this.arcgisCompositeIconFieldChange = createEvent(this, "arcgisCompositeIconFieldChange", 7);
    this.internalValues = {};
    this._schema = cloneObject(SCHEMA);
    this._uiSchema = cloneObject(UI_SCHEMA);
    this.values = {};
    this.isModalOpen = false;
    this.iconElements = [];
    this.selectedIcon = undefined;
    bind(this, 'translationFunc', 'handleOpenIconModal', 'handleSelectIcon', 'handleCloseIconModal', 'handleClickIcon', 'handleEditorChangeEvent');
  }
  async componentWillLoad() {
    var _a, _b;
    this.intl = await intlManager.loadIntlForComponent(this.element);
    this.selectedIcon = ((_b = (_a = this.values) === null || _a === void 0 ? void 0 : _a.icon) === null || _b === void 0 ? void 0 : _b.name) || '';
  }
  componentDidLoad() {
    // load the modal icons after the editor has loaded.
    // This speeds up the initial render
    this.loadIcons();
  }
  handleOpenIconModal() {
    this.isModalOpen = true;
  }
  handleCloseIconModal() {
    this.isModalOpen = false;
  }
  handleClickIcon(event) {
    this.selectedIcon = event.target.shadowRoot.querySelector('calcite-icon').getAttribute('icon');
  }
  handleSelectIcon() {
    this.internalValues = Object.assign(Object.assign({}, this.internalValues), { name: this.selectedIcon });
    this.isValid && this.arcgisCompositeIconFieldChange.emit(this.internalValues);
    this.isModalOpen = false;
  }
  handleEditorChangeEvent(event) {
    event.stopImmediatePropagation();
    event.stopPropagation();
    const { valid, values } = event.detail;
    this.internalValues = Object.assign(Object.assign({}, this.internalValues), values.icon);
    this.isValid = valid;
    if (valid) {
      this.arcgisCompositeIconFieldChange.emit(this.internalValues);
    }
  }
  loadIcons() {
    this.iconElements = iconNames.map((iconName) => {
      return h("calcite-action", { alignment: "center", icon: iconName, key: iconName, onClick: this.handleClickIcon, text: "" });
    });
  }
  translationFunc(key, values, opts) {
    return this.intl.t(key, values, opts);
  }
  render() {
    return (h(Host, null, h("arcgis-configuration-editor", { onArcgisConfigurationEditorChange: this.handleEditorChangeEvent, schema: this._schema, t: this.translationFunc, uiSchema: this._uiSchema, values: this.values }, h("div", { class: "select-icon", slot: "select-icon-button" }, h("calcite-button", { "icon-end": this.selectedIcon, onClick: this.handleOpenIconModal, width: "full" }, "Select an Icon"), h("arcgis-wormhole", null, h("calcite-modal", { onCalciteModalClose: this.handleCloseIconModal, open: this.isModalOpen, scale: "s" }, h("div", { slot: "header" }, this.intl.t('iconModalTitle')), h("div", { slot: "content" }, h("calcite-action-group", { columns: 6, layout: "grid" }, this.iconElements)), h("calcite-button", { appearance: "outline", onClick: this.handleCloseIconModal, slot: "secondary", width: "full" }, this.intl.t('cancel')), h("calcite-button", { disabled: !this.selectedIcon, onClick: this.handleSelectIcon, slot: "primary", width: "full" }, this.intl.t('select'))))))));
  }
  static get assetsDirs() { return ["locales"]; }
  get element() { return getElement(this); }
};

export { Icon as hub_composite_input_icon };
