import { HubEventAttendanceType, HubEventCapacityType } from "@esri/hub-common";
export const ENTITY = {
  id: "001",
  name: "event",
  type: "event",
  createdDate: new Date(),
  createdDateSource: "item.created",
  updatedDate: new Date(),
  updatedDateSource: "item.updated",
  orgUrlKey: "",
  access: "public",
  categories: [],
  description: "",
  itemControl: "public",
  owner: "fishingboatproceeds",
  schemaVersion: 4.0,
  tags: [],
  typeKeywords: [],
  canEdit: true,
  canDelete: true,
  allowRegistration: false,
  attendanceType: HubEventAttendanceType.Online,
  canChangeAccess: true,
  canChangeAccessOrg: true,
  canChangeAccessPrivate: true,
  canChangeAccessPublic: true,
  canChangeStatus: true,
  canChangeStatusCancelled: true,
  canChangeStatusRemoved: true,
  editGroupIds: [],
  endDate: new Date().toDateString(),
  endDateTime: new Date(),
  endTime: new Date().toTimeString(),
  isAllDay: true,
  isCanceled: false,
  isPlanned: true,
  isRemoved: false,
  notifyAttendees: false,
  onlineCapacityType: HubEventCapacityType.Unlimited,
  readGroupIds: [],
  references: [],
  startDate: new Date().toDateString(),
  startDateTime: new Date(),
  startTime: new Date().toTimeString(),
  timeZone: "EST"
};
