import { EventEmitter, VNode } from '../../stencil-public-runtime';
import { ComponentIntl } from '../../utils/stencil-intl';
import { HubEntity, HubEntityType } from '@esri/hub-common';
export declare class ArcgisHubLayoutEditorHeader {
  element: HTMLElement;
  intl: ComponentIntl;
  private get context();
  entity: HubEntity;
  site: HubEntity;
  saveButtonDisabled: boolean;
  isDirty: boolean;
  isPublishing: boolean;
  isSaving: boolean;
  showClone: boolean;
  showDelete: boolean;
  get type(): HubEntityType;
  get isSite(): boolean;
  get isPage(): boolean;
  get entityControls(): string[];
  arcgisHubLayoutEditorHeaderShare: EventEmitter<HubEntity>;
  arcgisHubLayoutEditorHeaderPreviewPublished: EventEmitter<HubEntity>;
  arcgisHubLayoutEditorHeaderPreviewDraft: EventEmitter<HubEntity>;
  arcgisHubLayoutEditorHeaderPublish: EventEmitter<HubEntity>;
  arcgisHubLayoutEditorHeaderSave: EventEmitter<HubEntity>;
  arcgisHubLayoutEditorHeaderClone: EventEmitter<HubEntity>;
  arcgisHubLayoutEditorHeaderDeleteDraft: EventEmitter<HubEntity>;
  arcgisHubLayoutEditorHeaderDelete: EventEmitter<HubEntity>;
  arcgisHubLayoutEditorHeaderSaveAsTemplate: EventEmitter<HubEntity>;
  hubTelemetry: EventEmitter<Record<string, any>>;
  componentWillLoad(): Promise<void>;
  handleWorkspaceItemClick: () => void;
  handleSiteMenuItemClick: () => void;
  handleAccessChange: () => void;
  handleEditS123ButtonClick: () => void;
  handleViewButtonClick: () => void;
  handlePreviewPublished: () => void;
  handlePreviewDraft: () => void;
  handlePublish: () => void;
  handleSave: () => void;
  handleOverflowButtonClick: () => void;
  handleClone: () => void;
  handleDeleteDraft: () => void;
  handleDelete: () => void;
  handleSaveAsTemplate: () => void;
  handleEditLayout: () => void;
  handleViewSite: () => void;
  get sharingButtonIcon(): string;
  get saveButtonIcon(): string;
  renderSitePopover(): VNode;
  get workspaceUrl(): string;
  renderMenus(): VNode;
  renderControls(): VNode;
  render(): any;
}
