import { IGroup, IPortal, IUser } from '@esri/arcgis-rest-portal';
import { IChannel, IPost } from '@esri/hub-discussions';
import { IArcGISContext } from '@esri/hub-common';
import { IMentionedUserDetails } from '../../../../utils/discussions/types';
export declare const GROUPS: IGroup[];
export declare const CHANNEL: IChannel;
export declare const POST: IPost;
export declare const CREATOR: IUser;
export declare const ORGANIZATION: IPortal;
export declare const CONTEXT: IArcGISContext;
export declare const MENTIONEDUSERS: IMentionedUserDetails[];
